// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj1K-llCuJQLQQnnD8x-PEyMQe6DeGuyk',
    appId: '1:835122226704:ios:00402e8326ddb22fe30c95',
    messagingSenderId: '835122226704',
    projectId: 'event-matching-1c7e1',
    storageBucket: 'event-matching-1c7e1.firebasestorage.app',
    iosBundleId: 'com.example.day1FlutterBasics',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6fwNZc7iKQVHZ70454wq6m9Q4dbkRTRQ',
    appId: '1:835122226704:web:f8000f081c3332b1e30c95',
    messagingSenderId: '835122226704',
    projectId: 'event-matching-1c7e1',
    authDomain: 'event-matching-1c7e1.firebaseapp.com',
    storageBucket: 'event-matching-1c7e1.firebasestorage.app',
    measurementId: 'G-QMNFE1SG9T',
  );
}
